eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.config.import=optional:classpath:config/gateway-service.properties,classpath:config/user-service.properties,classpath:config/auth-service.properties,classpath:config/academic-service.properties,classpath:config/course-service.properties
management.endpoints.web.exposure.include=refresh
eureka.instance.prefer-ip-address=false
