eureka.client.service-url.defaultZone=http://localhost:8761/eureka
app.jwt-secret=DayLaMotChuoiBiMatRatDaiVaAnToanDungDeKyTokenJWT
spring.cloud.gateway.discovery.locator.enabled=true


# Route [0]: Dành cho Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=Authentication

# Route [1]: Dành cho User Service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=Authentication

# Route [2]: Dành cho Course Service
spring.cloud.gateway.routes[2].id=course-service
spring.cloud.gateway.routes[2].uri=lb://course-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/courses/**, /api/classrooms/**
spring.cloud.gateway.routes[2].filters[0]=Authentication

# Route [3]: Dành cho Academic Service
spring.cloud.gateway.routes[3].id=academic-service
spring.cloud.gateway.routes[3].uri=lb://academic-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/assignments/**, /api/submissions/**, /api/notifications/**, /api/assignments/*/submissions, api/submissions/*/grade
spring.cloud.gateway.routes[3].filters[0]=Authentication

# Thêm route m?i, ví d?: Route [4]
spring.cloud.gateway.routes[4].id=actuator
spring.cloud.gateway.routes[4].uri=lb://user-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/actuator/**