# Tên c?a service này
spring.application.name=config-service
# C?ng m?c ??nh c?a Config Server
server.port=8888

# ??a ch? c?a Eureka Server ?? nó ??ng ký
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# --- C?U HÌNH K?T N?I T?I GIT REPO ---
# Thay b?ng URL c?a repository c?u hình mà b?n ?ã t?o trên GitHub/GitLab
spring.cloud.config.server.git.uri=https://github.com/dkt712004/trungtamtienganh-config.git