# Tên c?a service này khi ??ng ký lên Eureka
spring.application.name=config-service

# C?ng mà service này s? ch?y
server.port=8888

# ??a ch? c?a Eureka Server ?? nó có th? t? ??ng ký
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Kích ho?t profile "native" ?? Config Server ??c file t? classpath thay vì Git
spring.profiles.active=native

# Ch? ??nh th? m?c bên trong `resources` n?i ch?a các file c?u hình c?a các service khác
spring.cloud.config.server.native.search-locations=classpath:/config
